{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"authorship_tag":"ABX9TyMwMziAcJ6KO5YbmhAusCLw"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"code","execution_count":1,"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"7_BFcYsMTUPB","executionInfo":{"status":"ok","timestamp":1746546889544,"user_tz":-300,"elapsed":33,"user":{"displayName":"Anam Zakir","userId":"04567498634042558007"}},"outputId":"4f3fb9bd-35bb-46c0-e06c-c308cad93ceb"},"outputs":[{"output_type":"stream","name":"stdout","text":["Caught an exception: Invalid age: 16. Must be 18 or older.\n"]}],"source":["# Define custom exception\n","class InvalidAgeError(Exception):\n","    def __init__(self, message=\"Age must be 18 or older.\"):\n","        super().__init__(message)\n","\n","# Function that uses the custom exception\n","def check_age(age):\n","    if age < 18:\n","        raise InvalidAgeError(f\"Invalid age: {age}. Must be 18 or older.\")\n","    else:\n","        print(\"Age is valid.\")\n","\n","# Example usage with exception handling\n","try:\n","    check_age(16)\n","except InvalidAgeError as e:\n","    print(\"Caught an exception:\", e)\n"]}]}